### ISSUE TITLE
Similarities with kuberentes-sigs NFD`

### ISSUE THREAD

**Issue by ArangoGutierrez** [vKubeViewer/vkubeviewer#15]
Hey all! 

after reading 

> Upon initial 1.0 release, the project will be open sourced and the Kubernetes community is free to use and update the project with additional features and functionality.

What would you say about combining efforts on https://github.com/kubernetes-sigs/node-feature-discovery ?

**Comment by jarrywangcn** [comment]
hi ArangoGutierrez,  our repo are mostly related to the resources objects on VMware's vSphere.
So all of our information are retrieved from vSphere and follows vSphere's architecture (hosts, datacenter, virtual machines and so on..)
And our users are developers and administrators running k8s nodes on vSphere platform. so the logic between two repos seems quite different?
But we will take a close look about Kubernetes-sigs NFD,  thx your for your advice!

**Comment by cormachogan** [comment]
I agree with @jarrywangcn - this initiative is very much focused on K8s running on VMware vSphere, so any node information that we bubble up in our operators is focused purely on the assumption that a node is a VMware vSphere virtual machine. 

Appreciate you reaching out @ArangoGutierrez - if you feel that we might be missing some synergies between the different projects, please let us know.
